// src/lib/mstChain.ts
// MST Blockchain integration for AgriVision XR.
//
// - Network: MST Testnet (chain ID 91562037), RPC + explorer below.
// - Contract: AgriProvenance (contracts/AgriProvenance.sol), address from VITE_AGRI_MST_ADDRESS in .env.
// - ABI: src/lib/abi/AgriProvenance.json, generated by compiling contracts/AgriProvenance.sol with solc.
// - Signing happens in the user's wallet (MetaMask). This file never asks for, reads or stores a
//   private key or Secret Recovery Phrase, and needs no API key.
//
// Everything a UI shows about the chain comes from a wallet/RPC response. Nothing here fabricates
// transaction hashes, block numbers or verification results.
import {
  BrowserProvider,
  Contract,
  JsonRpcProvider,
  ZeroHash,
  getAddress,
  isAddress,
  keccak256,
  toUtf8Bytes,
} from "ethers";
import agriProvenanceArtifact from "./abi/AgriProvenance.json";
import {
  buildTree,
  getProof,
  verifyProof,
  dataHash,
  leafNode,
  type FieldRecord,
} from "./merkleSum";

// ---------------------------------------------------------------------------
// Network configuration
// ---------------------------------------------------------------------------
export const MST_CHAIN_ID = 91562037;

export const MST_TESTNET = {
  chainId: MST_CHAIN_ID,
  chainIdHex: "0x5752035", // 91562037
  chainName: "MST Testnet",
  rpcUrls: ["https://testnetrpc.mstblockchain.com"],
  nativeCurrency: { name: "MSTC", symbol: "MSTC", decimals: 18 },
  blockExplorerUrls: ["https://testnet.mstscan.com"],
  faucetUrl: "https://faucet.mstblockchain.com/",
};

const EXPLORER = MST_TESTNET.blockExplorerUrls[0];
export const explorerTxUrl = (hash: string) => `${EXPLORER}/tx/${hash}`;
export const explorerAddressUrl = (addr: string) => `${EXPLORER}/address/${addr}`;
export const explorerBlockUrl = (n: number | string) => `${EXPLORER}/block/${n}`;

// Real ABI produced by the Solidity compiler (see src/lib/abi/AgriProvenance.json).
export const AGRI_PROVENANCE_ABI = agriProvenanceArtifact.abi;

// Typed view of the three AgriProvenance functions, so strict TypeScript is happy.
interface AgriProvenanceContract {
  batches(batchId: string): Promise<{ root: string; totalGrams: bigint; farmer: string; anchoredAt: bigint }>;
  anchor: ((batchId: string, root: string, totalGrams: bigint) => Promise<any>) & {
    estimateGas: (batchId: string, root: string, totalGrams: bigint) => Promise<bigint>;
  };
  verify(
    batchId: string,
    recordDataHash: string,
    grams: bigint,
    sibHashes: string[],
    sibSums: bigint[],
    sibIsLeft: boolean[],
  ): Promise<boolean>;
}
function agri(address: string, runner: any): AgriProvenanceContract {
  return new Contract(address, AGRI_PROVENANCE_ABI, runner) as unknown as AgriProvenanceContract;
}

// ---------------------------------------------------------------------------
// Contract address (.env → VITE_AGRI_MST_ADDRESS). A contract address is public, not a secret.
// ---------------------------------------------------------------------------
export function getContractAddress(): string | null {
  const raw = (import.meta as any).env?.VITE_AGRI_MST_ADDRESS as string | undefined;
  const addr = raw?.trim();
  return addr ? addr : null;
}

function contractAddress(): string {
  const addr = getContractAddress();
  if (!addr) {
    throw new MstError(
      "CONTRACT_NOT_CONFIGURED",
      "Contract address missing. Add VITE_AGRI_MST_ADDRESS=0x... to the .env file in the project root, then restart the dev server.",
    );
  }
  if (!isAddress(addr)) {
    throw new MstError("CONTRACT_INVALID_ADDRESS", `VITE_AGRI_MST_ADDRESS is not a valid address: ${addr}`);
  }
  return getAddress(addr);
}

// ---------------------------------------------------------------------------
// Errors: every failure is mapped to a code the UI can show clearly.
// ---------------------------------------------------------------------------
export type MstErrorCode =
  | "NO_WALLET"
  | "CONNECT_REJECTED"
  | "REQUEST_PENDING"
  | "WRONG_NETWORK"
  | "TX_REJECTED"
  | "INSUFFICIENT_FUNDS"
  | "CONTRACT_NOT_CONFIGURED"
  | "CONTRACT_INVALID_ADDRESS"
  | "CONTRACT_NOT_DEPLOYED"
  | "CONTRACT_MISMATCH"
  | "ALREADY_ANCHORED"
  | "TX_FAILED"
  | "TX_PENDING"
  | "RPC_ERROR"
  | "UNKNOWN";

export class MstError extends Error {
  code: MstErrorCode;
  constructor(code: MstErrorCode, message: string) {
    super(message);
    this.code = code;
    this.name = "MstError";
  }
}

function rawCode(e: any): unknown {
  return e?.info?.error?.code ?? e?.error?.code ?? e?.code;
}

export function toMstError(e: any, context: "connect" | "switch" | "tx" | "read" = "read"): MstError {
  if (e instanceof MstError || e?.name === "MstError") return e as MstError;
  const code = rawCode(e);
  const msg = String(e?.shortMessage || e?.info?.error?.message || e?.message || e);
  const low = msg.toLowerCase();

  if (code === "ACTION_REJECTED" || code === 4001 || low.includes("user rejected") || low.includes("user denied")) {
    if (context === "tx") return new MstError("TX_REJECTED", "Transaction rejected in MetaMask. Nothing was sent to MST Testnet.");
    if (context === "switch") return new MstError("WRONG_NETWORK", "Network switch was rejected. Please switch to MST Testnet.");
    return new MstError("CONNECT_REJECTED", "Wallet connection was rejected in MetaMask.");
  }
  if (code === -32002) {
    return new MstError("REQUEST_PENDING", "A MetaMask request is already open. Open the MetaMask extension to finish it.");
  }
  if (code === "INSUFFICIENT_FUNDS" || low.includes("insufficient funds")) {
    return new MstError(
      "INSUFFICIENT_FUNDS",
      `Insufficient MSTC for gas. Get test MSTC from the faucet: ${MST_TESTNET.faucetUrl}`,
    );
  }
  if (low.includes("batch exists")) {
    return new MstError("ALREADY_ANCHORED", "This activity is already recorded on-chain (the contract rejected a duplicate).");
  }
  if (code === "CALL_EXCEPTION") {
    return new MstError("TX_FAILED", `Contract call reverted: ${e?.reason || msg}`);
  }
  if (code === "TIMEOUT") {
    return new MstError("TX_PENDING", "Transaction is still pending on MST Testnet. Re-check it from the Activity Ledger.");
  }
  if (
    code === "NETWORK_ERROR" ||
    code === "SERVER_ERROR" ||
    code === -32603 ||
    low.includes("failed to fetch") ||
    low.includes("could not detect network") ||
    low.includes("network error")
  ) {
    return new MstError("RPC_ERROR", `Could not reach the MST Testnet RPC (${MST_TESTNET.rpcUrls[0]}). ${msg}`);
  }
  return new MstError("UNKNOWN", msg);
}

// ---------------------------------------------------------------------------
// Providers
// ---------------------------------------------------------------------------
function injected(): any | null {
  if (typeof window === "undefined") return null;
  return (window as any).ethereum ?? null;
}

export function hasWallet(): boolean {
  return !!injected();
}

let readProvider: JsonRpcProvider | null = null;
function getReadProvider(): JsonRpcProvider {
  if (!readProvider) {
    readProvider = new JsonRpcProvider(MST_TESTNET.rpcUrls[0], MST_CHAIN_ID, { staticNetwork: true });
  }
  return readProvider;
}

function walletProvider(): BrowserProvider {
  const eth = injected();
  if (!eth) throw new MstError("NO_WALLET", "MetaMask is not installed. Install MetaMask (or another EVM browser wallet) and reload.");
  // "any" lets the provider survive network switches instead of throwing "network changed".
  return new BrowserProvider(eth, "any");
}

// Reads go through the wallet if it is on MST Testnet (no CORS issues), otherwise the public RPC.
async function bestReadProvider(): Promise<BrowserProvider | JsonRpcProvider> {
  try {
    const eth = injected();
    if (eth) {
      const hex = await eth.request({ method: "eth_chainId" });
      if (parseInt(hex, 16) === MST_CHAIN_ID) return walletProvider();
    }
  } catch {
    /* fall back to public RPC */
  }
  return getReadProvider();
}

// ---------------------------------------------------------------------------
// Wallet
// ---------------------------------------------------------------------------
export interface WalletState {
  hasWallet: boolean;
  address: string | null;
  chainId: number | null;
  onMst: boolean;
}

// Reads the current state WITHOUT opening a MetaMask prompt.
export async function getWalletState(): Promise<WalletState> {
  const eth = injected();
  if (!eth) return { hasWallet: false, address: null, chainId: null, onMst: false };
  try {
    const [accounts, hex] = await Promise.all([
      eth.request({ method: "eth_accounts" }),
      eth.request({ method: "eth_chainId" }),
    ]);
    const chainId = parseInt(hex, 16);
    const address = accounts?.[0] ? getAddress(accounts[0]) : null;
    return { hasWallet: true, address, chainId, onMst: chainId === MST_CHAIN_ID };
  } catch {
    return { hasWallet: true, address: null, chainId: null, onMst: false };
  }
}

// "Connect MST Wallet": asks MetaMask for an account, then reports the chain.
// It does NOT silently switch networks; the UI shows "Please switch to MST Testnet" and offers a button.
export async function connectWallet(): Promise<WalletState> {
  const eth = injected();
  if (!eth) throw new MstError("NO_WALLET", "MetaMask is not installed. Install MetaMask (or another EVM browser wallet) and reload.");
  try {
    await eth.request({ method: "eth_requestAccounts" });
  } catch (e) {
    throw toMstError(e, "connect");
  }
  return getWalletState();
}

// Switches MetaMask to MST Testnet; adds the network first if MetaMask does not know it (error 4902).
export async function switchToMst(): Promise<WalletState> {
  const eth = injected();
  if (!eth) throw new MstError("NO_WALLET", "MetaMask is not installed.");
  try {
    await eth.request({ method: "wallet_switchEthereumChain", params: [{ chainId: MST_TESTNET.chainIdHex }] });
  } catch (e: any) {
    const code = rawCode(e);
    const unknownChain = code === 4902 || String(e?.message || "").includes("Unrecognized chain");
    if (!unknownChain) throw toMstError(e, "switch");
    try {
      await eth.request({
        method: "wallet_addEthereumChain",
        params: [
          {
            chainId: MST_TESTNET.chainIdHex,
            chainName: MST_TESTNET.chainName,
            rpcUrls: MST_TESTNET.rpcUrls,
            nativeCurrency: MST_TESTNET.nativeCurrency,
            blockExplorerUrls: MST_TESTNET.blockExplorerUrls,
          },
        ],
      });
    } catch (e2) {
      throw toMstError(e2, "switch");
    }
  }
  return getWalletState();
}

// Revokes this site's account permission in MetaMask (supported by current MetaMask versions).
// Wallets that do not support it simply keep the permission; the app still forgets the session.
export async function disconnectWallet(): Promise<{ revoked: boolean }> {
  const eth = injected();
  if (!eth) return { revoked: false };
  try {
    await eth.request({ method: "wallet_revokePermissions", params: [{ eth_accounts: {} }] });
    return { revoked: true };
  } catch {
    return { revoked: false };
  }
}

export function onWalletEvents(cb: (s: WalletState) => void): () => void {
  const eth = injected();
  if (!eth?.on) return () => {};
  const handler = () => {
    getWalletState().then(cb);
  };
  eth.on("accountsChanged", handler);
  eth.on("chainChanged", handler);
  return () => {
    eth.removeListener?.("accountsChanged", handler);
    eth.removeListener?.("chainChanged", handler);
  };
}

export async function getMstcBalance(address: string): Promise<string> {
  const p = await bestReadProvider();
  const wei = await p.getBalance(address);
  return (Number(wei) / 1e18).toFixed(4);
}

// Backward-compatible helper (used by anchorBatch / verifyRecord): connect + switch + signer.
export async function connectMst() {
  await connectWallet();
  const state = await switchToMst();
  if (!state.onMst) throw new MstError("WRONG_NETWORK", "Please switch to MST Testnet.");
  const provider = walletProvider();
  const signer = await provider.getSigner();
  return { provider, signer, address: await signer.getAddress() };
}

// ---------------------------------------------------------------------------
// Network + contract status (real RPC reads)
// ---------------------------------------------------------------------------
export interface NetworkStatus {
  ok: boolean;
  chainId: number | null;
  blockNumber: number | null;
  via: "wallet" | "public-rpc";
  error?: string;
}

export async function getNetworkStatus(): Promise<NetworkStatus> {
  const p = await bestReadProvider();
  const via = p instanceof BrowserProvider ? "wallet" : "public-rpc";
  try {
    const [net, blockNumber] = await Promise.all([p.getNetwork(), p.getBlockNumber()]);
    return { ok: Number(net.chainId) === MST_CHAIN_ID, chainId: Number(net.chainId), blockNumber, via };
  } catch (e) {
    return { ok: false, chainId: null, blockNumber: null, via, error: toMstError(e).message };
  }
}

export type ContractState =
  | "missing_address"
  | "invalid_address"
  | "not_deployed"
  | "abi_mismatch"
  | "deployed"
  | "rpc_error";

export interface ContractStatus {
  state: ContractState;
  address: string | null;
  message: string;
}

export async function getContractStatus(): Promise<ContractStatus> {
  const raw = getContractAddress();
  if (!raw) {
    return {
      state: "missing_address",
      address: null,
      message: "Not deployed / not configured: set VITE_AGRI_MST_ADDRESS in .env",
    };
  }
  if (!isAddress(raw)) return { state: "invalid_address", address: raw, message: "Invalid address in VITE_AGRI_MST_ADDRESS" };
  const address = getAddress(raw);
  try {
    const p = await bestReadProvider();
    const code = await p.getCode(address);
    if (!code || code === "0x") {
      return { state: "not_deployed", address, message: "Not deployed: no contract code at this address on MST Testnet" };
    }
    // Probe the ABI: batches(bytes32) must decode as AgriProvenance's struct.
    try {
      const c = agri(address, p);
      await c.batches(ZeroHash);
    } catch {
      return {
        state: "abi_mismatch",
        address,
        message: "A contract exists here, but it does not respond like AgriProvenance",
      };
    }
    return { state: "deployed", address, message: "Deployed on MST Testnet" };
  } catch (e) {
    return { state: "rpc_error", address, message: toMstError(e).message };
  }
}

// ---------------------------------------------------------------------------
// Farm activity hashing
// ---------------------------------------------------------------------------
export const ACTIVITY_TYPES = [
  "FARM_CREATED",
  "CROP_ANALYZED",
  "AI_RECOMMENDATION",
  "TRAINING_COMPLETED",
  "FARM_ACTION",
  "CREDENTIAL_ISSUED",
] as const;
export type ActivityType = (typeof ACTIVITY_TYPES)[number];

export interface FarmActivity {
  activityId: string; // e.g. AGRI-001-CROP_ANALYZED-1727600000000
  activityType: ActivityType;
  farmId: string;
  timestamp: number; // ms
  payload: Record<string, unknown>; // compact, non-personal summary. Stays in the browser.
}

// Never allow obviously personal fields into the hashed payload.
const BLOCKED_KEYS = /name|email|phone|mobile|address|image|photo|img|base64|password|aadhaar|dob/i;
function sanitizePayload(p: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(p || {})) {
    if (BLOCKED_KEYS.test(k)) continue;
    if (typeof v === "string") out[k] = v.slice(0, 200);
    else if (typeof v === "number" || typeof v === "boolean" || v === null) out[k] = v;
  }
  return out;
}

function toFieldRecord(a: FarmActivity): FieldRecord {
  return {
    id: a.activityId,
    type: a.activityType as unknown as FieldRecord["type"],
    payload: { farmId: a.farmId, ...sanitizePayload(a.payload) },
    grams: 0,
    ts: a.timestamp,
  };
}

export interface ActivityHash {
  dataHash: string; // keccak256 of the canonical JSON of the activity (this is what the ledger shows)
  batchId: string; // keccak256(activityId): the on-chain key
  root: string; // single-leaf Merkle Sum Tree root = keccak256(dataHash, 0): the value stored on-chain
  canonicalPayload: Record<string, unknown>;
}

export function prepareActivity(input: Omit<FarmActivity, "activityId" | "timestamp"> & Partial<FarmActivity>): FarmActivity {
  const timestamp = input.timestamp ?? Date.now();
  return {
    activityId: input.activityId ?? `${input.farmId}-${input.activityType}-${timestamp}`,
    activityType: input.activityType,
    farmId: input.farmId,
    timestamp,
    payload: sanitizePayload(input.payload || {}),
  };
}

export function hashActivity(a: FarmActivity): ActivityHash {
  const rec = toFieldRecord(a);
  return {
    dataHash: dataHash(rec),
    batchId: batchIdFromName(a.activityId),
    root: leafNode(rec).hash,
    canonicalPayload: rec.payload,
  };
}

export function batchIdFromName(name: string): string {
  return keccak256(toUtf8Bytes(name));
}

// ---------------------------------------------------------------------------
// Ledger (browser storage). Records are only ever created from real transaction receipts.
// ---------------------------------------------------------------------------
export type LedgerStatus = "PENDING" | "CONFIRMED" | "FAILED";

export interface LedgerRecord {
  activityId: string;
  activityType: ActivityType;
  farmId: string;
  timestamp: number;
  payload: Record<string, unknown>;
  dataHash: string;
  batchId: string;
  root: string;
  wallet: string;
  contract: string;
  chainId: number;
  txHash: string;
  blockNumber: number | null;
  gasUsed: string | null;
  status: LedgerStatus;
  submittedAt: number;
}

const LEDGER_KEY = "agrivision_mst_ledger_v1";

export function loadLedger(): LedgerRecord[] {
  try {
    const arr = JSON.parse(localStorage.getItem(LEDGER_KEY) || "[]");
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

function saveLedgerRecord(r: LedgerRecord) {
  const all = loadLedger().filter((x) => x.txHash !== r.txHash);
  all.unshift(r);
  localStorage.setItem(LEDGER_KEY, JSON.stringify(all.slice(0, 200)));
}

// ---------------------------------------------------------------------------
// VERIFY ON MST: sends a real transaction to AgriProvenance.anchor(batchId, root, 0)
// ---------------------------------------------------------------------------
export type VerifyPhase =
  | { phase: "preflight"; message: string }
  | { phase: "awaiting_signature"; message: string }
  | { phase: "submitted"; txHash: string; explorerUrl: string }
  | { phase: "confirmed"; record: LedgerRecord };

export async function verifyActivityOnMst(
  activity: FarmActivity,
  onUpdate: (u: VerifyPhase) => void = () => {},
): Promise<LedgerRecord> {
  onUpdate({ phase: "preflight", message: "Checking wallet, network and contract…" });

  // 1. Wallet + network
  const state = await getWalletState();
  if (!state.hasWallet) throw new MstError("NO_WALLET", "MetaMask is not installed.");
  if (!state.address) throw new MstError("CONNECT_REJECTED", "Connect your wallet first (Connect MST Wallet).");
  if (!state.onMst) throw new MstError("WRONG_NETWORK", "Please switch to MST Testnet (chain ID 91562037).");

  // 2. Contract
  const status = await getContractStatus();
  if (status.state === "missing_address") throw new MstError("CONTRACT_NOT_CONFIGURED", status.message);
  if (status.state === "invalid_address") throw new MstError("CONTRACT_INVALID_ADDRESS", status.message);
  if (status.state === "not_deployed") throw new MstError("CONTRACT_NOT_DEPLOYED", status.message);
  if (status.state === "abi_mismatch") throw new MstError("CONTRACT_MISMATCH", status.message);
  if (status.state === "rpc_error") throw new MstError("RPC_ERROR", status.message);

  const address = contractAddress();
  const provider = walletProvider();
  const signer = await provider.getSigner();
  const from = await signer.getAddress();
  const contract = agri(address, signer);
  const h = hashActivity(activity);

  // 3. Duplicate check (the contract would revert with "batch exists")
  try {
    const existing = await contract.batches(h.batchId);
    if (existing.anchoredAt !== 0n) {
      throw new MstError("ALREADY_ANCHORED", "This activity ID is already recorded on MST Testnet.");
    }
  } catch (e) {
    throw toMstError(e, "read");
  }

  // 4. Gas + balance check (clear "Insufficient MSTC" instead of a cryptic wallet error)
  try {
    const [gas, fee, balance] = await Promise.all([
      contract.anchor.estimateGas(h.batchId, h.root, 0n),
      provider.getFeeData(),
      provider.getBalance(from),
    ]);
    const price = fee.maxFeePerGas ?? fee.gasPrice ?? 0n;
    if (price > 0n && balance < gas * price) {
      throw new MstError(
        "INSUFFICIENT_FUNDS",
        `Insufficient MSTC for gas. Get test MSTC from the faucet: ${MST_TESTNET.faucetUrl}`,
      );
    }
  } catch (e) {
    throw toMstError(e, "tx");
  }

  // 5. Send (MetaMask pops up)
  onUpdate({ phase: "awaiting_signature", message: "Confirm the transaction in MetaMask…" });
  let tx: any;
  try {
    tx = await contract.anchor(h.batchId, h.root, 0n);
  } catch (e) {
    throw toMstError(e, "tx");
  }

  const base: LedgerRecord = {
    activityId: activity.activityId,
    activityType: activity.activityType,
    farmId: activity.farmId,
    timestamp: activity.timestamp,
    payload: h.canonicalPayload,
    dataHash: h.dataHash,
    batchId: h.batchId,
    root: h.root,
    wallet: from,
    contract: address,
    chainId: MST_CHAIN_ID,
    txHash: tx.hash,
    blockNumber: null,
    gasUsed: null,
    status: "PENDING",
    submittedAt: Date.now(),
  };
  saveLedgerRecord(base); // saved as PENDING with the real hash, so a reload can re-check it
  onUpdate({ phase: "submitted", txHash: tx.hash, explorerUrl: explorerTxUrl(tx.hash) });

  // 6. Wait for the receipt
  let receipt: any;
  try {
    receipt = await tx.wait(1, 180_000);
  } catch (e: any) {
    const err = toMstError(e, "tx");
    if (err.code === "TX_FAILED" || e?.receipt?.status === 0) {
      saveLedgerRecord({ ...base, status: "FAILED", blockNumber: e?.receipt?.blockNumber ?? null });
    }
    throw err;
  }
  if (!receipt || receipt.status !== 1) {
    saveLedgerRecord({ ...base, status: "FAILED", blockNumber: receipt?.blockNumber ?? null });
    throw new MstError("TX_FAILED", "Transaction failed on MST Testnet (receipt status 0).");
  }

  const confirmed: LedgerRecord = {
    ...base,
    wallet: getAddress(receipt.from),
    blockNumber: receipt.blockNumber,
    gasUsed: receipt.gasUsed.toString(),
    status: "CONFIRMED",
  };
  saveLedgerRecord(confirmed);
  onUpdate({ phase: "confirmed", record: confirmed });
  return confirmed;
}

// ---------------------------------------------------------------------------
// Re-check a saved record against the chain (receipt + stored root + contract.verify)
// ---------------------------------------------------------------------------
export interface RecheckResult {
  receiptFound: boolean;
  receiptStatus: "success" | "failed" | "pending";
  blockNumber: number | null;
  gasUsed: string | null;
  from: string | null;
  toMatchesContract: boolean;
  storedRootMatches: boolean;
  contractVerify: boolean; // AgriProvenance.verify(batchId, dataHash, 0, [], [], [])
  error?: string;
}

export async function recheckRecord(r: LedgerRecord): Promise<RecheckResult> {
  const result: RecheckResult = {
    receiptFound: false,
    receiptStatus: "pending",
    blockNumber: null,
    gasUsed: null,
    from: null,
    toMatchesContract: false,
    storedRootMatches: false,
    contractVerify: false,
  };
  try {
    const p = await bestReadProvider();
    const receipt = await p.getTransactionReceipt(r.txHash);
    if (!receipt) return result;
    result.receiptFound = true;
    result.receiptStatus = receipt.status === 1 ? "success" : "failed";
    result.blockNumber = receipt.blockNumber;
    result.gasUsed = receipt.gasUsed.toString();
    result.from = receipt.from;
    result.toMatchesContract = !!receipt.to && receipt.to.toLowerCase() === r.contract.toLowerCase();
    if (receipt.status !== 1) return result;

    const c = agri(r.contract, p);
    const stored = await c.batches(r.batchId);
    result.storedRootMatches = String(stored.root).toLowerCase() === r.root.toLowerCase();
    result.contractVerify = await c.verify(r.batchId, r.dataHash, 0n, [], [], []);

    // Keep the local copy in sync with what the chain says.
    const all = loadLedger();
    const i = all.findIndex((x) => x.txHash === r.txHash);
    const cur = i >= 0 ? all[i] : undefined;
    if (cur) {
      all[i] = {
        ...cur,
        status: "CONFIRMED",
        blockNumber: receipt.blockNumber,
        gasUsed: receipt.gasUsed.toString(),
        wallet: getAddress(receipt.from),
      };
      localStorage.setItem(LEDGER_KEY, JSON.stringify(all));
    }
    return result;
  } catch (e) {
    return { ...result, error: toMstError(e).message };
  }
}

// Tamper test: change one field of the activity and ask the contract to verify it. Must return false.
export async function tamperCheck(r: LedgerRecord): Promise<{ original: boolean; tampered: boolean; tamperedHash: string }> {
  const p = await bestReadProvider();
  const c = agri(r.contract, p);
  const tamperedRec: FieldRecord = {
    id: r.activityId,
    type: r.activityType as unknown as FieldRecord["type"],
    payload: { ...r.payload, tampered: true },
    grams: 0,
    ts: r.timestamp,
  };
  const tamperedHash = dataHash(tamperedRec);
  const [original, tampered] = await Promise.all([
    c.verify(r.batchId, r.dataHash, 0n, [], [], []),
    c.verify(r.batchId, tamperedHash, 0n, [], [], []),
  ]);
  return { original, tampered, tamperedHash };
}

// ---------------------------------------------------------------------------
// Original batch helpers (Merkle Sum Tree over many records), kept for compatibility.
// ---------------------------------------------------------------------------
export async function anchorBatch(batchName: string, records: FieldRecord[]) {
  const { signer } = await connectMst();
  const tree = buildTree(records);
  const batchId = batchIdFromName(batchName);
  const contract = agri(contractAddress(), signer);
  const tx = await contract.anchor(batchId, tree.root.hash, tree.root.sum);
  await tx.wait();
  return {
    batchId,
    root: tree.root.hash,
    totalGrams: tree.root.sum.toString(),
    txHash: tx.hash as string,
    explorerUrl: explorerTxUrl(tx.hash),
  };
}

export async function verifyRecord(batchName: string, records: FieldRecord[], index: number) {
  const { provider } = await connectMst();
  const contract = agri(contractAddress(), provider);
  const batchId = batchIdFromName(batchName);
  const stored = await contract.batches(batchId);
  if (stored.anchoredAt === 0n) return { found: false, localOk: false, onChainOk: false };

  const tree = buildTree(records);
  const proof = getProof(tree, index);
  const record = records[index];
  if (!record) throw new Error(`No record at index ${index}`);

  const localOk = verifyProof(record, proof, stored.root, stored.totalGrams);
  const onChainOk: boolean = await contract.verify(
    batchId,
    dataHash(record),
    BigInt(Math.round(record.grams)),
    proof.map((s) => s.hash),
    proof.map((s) => BigInt(s.sum)),
    proof.map((s) => s.side === "left"),
  );
  return { found: true, localOk, onChainOk };
}

export async function tamperTest(batchName: string, records: FieldRecord[], index: number) {
  const bad = records.map((r, i) => (i === index ? { ...r, payload: { ...r.payload, tampered: true } } : r));
  return verifyRecord(batchName, bad, index);
}

// ---------------------------------------------------------------------------
// Bridge for the static public/agrivision.html (rendered in an iframe on the same origin).
// It calls these as window.parent.AgriMst.*
// ---------------------------------------------------------------------------
if (typeof window !== "undefined") {
  (window as any).AgriMst = {
    MST_TESTNET,
    MST_CHAIN_ID,
    ACTIVITY_TYPES,
    explorerTxUrl,
    explorerAddressUrl,
    explorerBlockUrl,
    getContractAddress,
    hasWallet,
    getWalletState,
    connectWallet,
    switchToMst,
    disconnectWallet,
    onWalletEvents,
    getMstcBalance,
    getNetworkStatus,
    getContractStatus,
    prepareActivity,
    hashActivity,
    verifyActivityOnMst,
    loadLedger,
    recheckRecord,
    tamperCheck,
    // original API
    connectMst,
    anchorBatch,
    verifyRecord,
    tamperTest,
    batchIdFromName,
  };
  window.dispatchEvent(new Event("agrimst:ready"));
}
