/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ApiAssessmentsRouteImport } from './routes/api/assessments'
import { Route as ApiScansRouteImport } from './routes/api/scans'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiDbStatusRouteImport } from './routes/api/db/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsRoute = ApiAssessmentsRouteImport.update({
  id: '/api/assessments',
  path: '/api/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScansRoute = ApiScansRouteImport.update({
  id: '/api/scans',
  path: '/api/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbStatusRoute = ApiDbStatusRouteImport.update({
  id: '/api/db/status',
  path: '/api/db/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/assessments': typeof ApiAssessmentsRoute
  '/api/scans': typeof ApiScansRoute
  '/api/users': typeof ApiUsersRoute
  '/api/db/status': typeof ApiDbStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/assessments': typeof ApiAssessmentsRoute
  '/api/scans': typeof ApiScansRoute
  '/api/users': typeof ApiUsersRoute
  '/api/db/status': typeof ApiDbStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/assessments': typeof ApiAssessmentsRoute
  '/api/scans': typeof ApiScansRoute
  '/api/users': typeof ApiUsersRoute
  '/api/db/status': typeof ApiDbStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/assessments'
    | '/api/scans'
    | '/api/users'
    | '/api/db/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/assessments'
    | '/api/scans'
    | '/api/users'
    | '/api/db/status'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/api/assessments'
    | '/api/scans'
    | '/api/users'
    | '/api/db/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAssessmentsRoute: typeof ApiAssessmentsRoute
  ApiScansRoute: typeof ApiScansRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiDbStatusRoute: typeof ApiDbStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments': {
      id: '/api/assessments'
      path: '/api/assessments'
      fullPath: '/api/assessments'
      preLoaderRoute: typeof ApiAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scans': {
      id: '/api/scans'
      path: '/api/scans'
      fullPath: '/api/scans'
      preLoaderRoute: typeof ApiScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/status': {
      id: '/api/db/status'
      path: '/api/db/status'
      fullPath: '/api/db/status'
      preLoaderRoute: typeof ApiDbStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAssessmentsRoute: ApiAssessmentsRoute,
  ApiScansRoute: ApiScansRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiDbStatusRoute: ApiDbStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
